### ISSUE TITLE
Facing issue while run application

### ISSUE THREAD

**Issue by testingcare** [GetStream/Livestream-Clone-Android#1]
While I am running these code, 
And having pop up setting error.
 {"error":{"code":5,"message":"Connect failed with error: \"JWTAuth error: token contains an invalid number of segments\"","StatusCode":401,"duration":"0.00ms","more_info":""}}

**Comment by JcMinarro** [comment]
Hello.

The error you are having is because the user token you are using is not valid.
We have moved this sample into our [Android Samples repository](https://github.com/GetStream/Android-Samples)
